name: 'apple_search_ads'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  apple_search_ads:
    organization: "{{ ref('stg_apple_search_ads__organization') }}"
    campaign_history: "{{ ref('stg_apple_search_ads__campaign_history') }}"
    campaign_report: "{{ ref('stg_apple_search_ads__campaign_report') }}"
    ad_group_history: "{{ ref('stg_apple_search_ads__ad_group_history') }}"
    ad_group_report: "{{ ref('stg_apple_search_ads__ad_group_report') }}"
    keyword_history: "{{ ref('stg_apple_search_ads__keyword_history') }}"
    keyword_report: "{{ ref('stg_apple_search_ads__keyword_report') }}"
    creative_set_report: "{{ ref('stg_apple_search_ads__creative_set_report') }}"
    search_term_report: "{{ ref('stg_apple_search_ads__search_term_report') }}"

    apple_search_ads__using_search_terms: true
    apple_search_ads__adapter: false ## placeholder for ad_reporting package
    
models:
  apple_search_ads_source:
    materialized: table
    +schema: apple_search_ads
    tmp:
      materialized: view

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  apple_search_ads_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    ad_group_history_data: 
      +column_types:
        modification_time: timestamp
        start_time: timestamp
        end_time: timestamp
    campaign_history_data:
      +column_types:
        modification_time: timestamp
        start_time: timestamp
        end_time: timestamp
    keyword_history_data:
      +column_types:
        modification_time: timestamp
    creative_set_report_data:
      +column_types:
        modification_time: timestamp
        creation_time: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']