config-version: 2

name: 'apple_search_ads_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']